name: Event Logging

on:
  issues

jobs:
  log_event:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event
        run: |
          echo "Trigger - ${{ github.event_name }}, user - ${{ github.actor }}, date - $(date)"
